allowBuilds:
  unrs-resolver: true
packageExtensions:
  '@stryker-mutator/core':
    dependencies:
      typescript: ^6.0.3
minimumReleaseAgeExclude:
  - '@chubbyts/chubbyts-dic-config-factory@1.0.0'
  - '@chubbyts/chubbyts-decode-encode@2.5.1'
  - '@chubbyts/chubbyts-negotiation@4.5.1'
